import { CodeGroupTabs } from '../../src/index';

import { CodeBlock, InlineCode, Page, pageParameters, Section, Table, Td, Th } from './StoryDocs';

const contentlayerSetup = `import rehypeCodeGroup from 'rehype-code-group-next';
import rehypePrettyCode from 'rehype-pretty-code';

export default makeSource({
  mdx: {
    rehypePlugins: [
      rehypeCodeGroup,
      [rehypePrettyCode, { theme: 'aurora-x' }]
    ]
  }
});`;

const layoutSetup = `import { CodeGroupTabs } from '@gaudi/design-system';

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <CodeGroupTabs />
        {children}
      </body>
    </html>
  );
}`;

const mdxFenceUsage = '```js title="app/page.js" {2}\nimport { Button } from \'@gaudi/design-system\';\n\nexport default function Page() {\n  return <Button>Read article</Button>;\n}\n```';

const mdxTabbedUsage = '```js:app/page.js\nexport default function Page() {\n  return <main>Article</main>;\n}\n```\n\n```tsx:app/page.tsx\nexport default function Page() {\n  return <main>Article</main>;\n}\n```';

const Keyword = ({ children }) => <span className='text-purple-300'>{children}</span>;
const ComponentToken = ({ children }) => <span className='text-blue-300'>{children}</span>;
const TagToken = ({ children }) => <span className='text-sky-300'>{children}</span>;
const StringToken = ({ children }) => <span className='text-green-300'>{children}</span>;
const PunctuationToken = ({ children }) => <span className='text-gray-500'>{children}</span>;

const DemoPre = ({ children }) => (
  <pre className='overflow-auto whitespace-pre rounded-b-md bg-gray-950 p-4 text-left text-sm leading-6 text-gray-100'>
    <code>{children}</code>
  </pre>
);

const DemoCodeGroup = () => (
  <div className='max-w-3xl'>
    <CodeGroupTabs />
    <div className='rehype-code-group'>
      <div className='rcg-tab-container' role='tablist' aria-label='Code language'>
        <button type='button' className='rcg-tab active' aria-selected='true'>JavaScript</button>
        <button type='button' className='rcg-tab' aria-selected='false'>TypeScript</button>
      </div>
      <div className='rcg-block active'>
        <DemoPre>
          <Keyword>import</Keyword>{' { '}<ComponentToken>Button</ComponentToken>{' } '}<Keyword>from</Keyword>{' '}<StringToken>'@gaudi/design-system'</StringToken><PunctuationToken>;</PunctuationToken>{'\n\n'}
          <Keyword>export</Keyword>{' '}<Keyword>default</Keyword>{' '}<Keyword>function</Keyword>{' '}<ComponentToken>Page</ComponentToken><PunctuationToken>() {'{'} </PunctuationToken>{'\n'}
          {'  '}<Keyword>return</Keyword>{' '}<TagToken>{'<Button>'}</TagToken>Read article<TagToken>{'</Button>'}</TagToken><PunctuationToken>;</PunctuationToken>{'\n'}
          <PunctuationToken>{'}'}</PunctuationToken>
        </DemoPre>
      </div>
      <div className='rcg-block' hidden>
        <DemoPre>
          <Keyword>import</Keyword>{' { '}<ComponentToken>Button</ComponentToken>{' } '}<Keyword>from</Keyword>{' '}<StringToken>'@gaudi/design-system'</StringToken><PunctuationToken>;</PunctuationToken>{'\n\n'}
          <Keyword>export</Keyword>{' '}<Keyword>default</Keyword>{' '}<Keyword>function</Keyword>{' '}<ComponentToken>Page</ComponentToken><PunctuationToken>()</PunctuationToken>{': '}<ComponentToken>JSX</ComponentToken><PunctuationToken>.</PunctuationToken><ComponentToken>Element</ComponentToken>{' '}<PunctuationToken>{'{'}</PunctuationToken>{'\n'}
          {'  '}<Keyword>return</Keyword>{' '}<TagToken>{'<Button>'}</TagToken>Read article<TagToken>{'</Button>'}</TagToken><PunctuationToken>;</PunctuationToken>{'\n'}
          <PunctuationToken>{'}'}</PunctuationToken>
        </DemoPre>
      </div>
    </div>
  </div>
);

const CodeHighlightingDocs = () => (
  <Page
    kicker='MDX'
    title='Code Highlighting'
    intro='Gaudi code blocks are generated by the MDX pipeline, styled by the MDX content layer, and enhanced by small client runtimes for copy buttons and tabbed code groups.'
  >
    <Section
      title='Pipeline'
      description='Keep syntax highlighting in the content pipeline. The design system owns the rendered code surface, but Shiki themes are configured where MDX is compiled.'
    >
      <Table>
        <thead>
          <tr><Th>Layer</Th><Th>Responsibility</Th><Th>Current contract</Th></tr>
        </thead>
        <tbody>
          <tr><Td mono>rehype-pretty-code</Td><Td>Converts fenced code blocks into Shiki-highlighted HTML.</Td><Td><InlineCode>theme: 'aurora-x'</InlineCode></Td></tr>
          <tr><Td mono>Pre</Td><Td>Wraps MDX <InlineCode>pre</InlineCode> output with copy-to-clipboard behavior.</Td><Td>Registered in the MDX component map as <InlineCode>pre: Pre</InlineCode>.</Td></tr>
          <tr><Td mono>CodeGroupTabs</Td><Td>Hydrates generated <InlineCode>.rehype-code-group</InlineCode> blocks and switches active tabs.</Td><Td>Mount once in the app layout.</Td></tr>
          <tr><Td mono>MdxContent</Td><Td>Scopes highlighted lines, highlighted chars, figures, captions, and tabbed-code spacing.</Td><Td>Use the MDX content wrapper around article output.</Td></tr>
        </tbody>
      </Table>
    </Section>

    <Section title='Theme Setup' description='Theme choice belongs in Contentlayer because syntax tokens are emitted at compile time.'>
      <CodeBlock code={ contentlayerSetup } language='js' />
    </Section>

    <Section title='Runtime Setup' description='Tabbed code groups need one client runtime mounted near the app root. Do not mount it per code block.'>
      <CodeBlock code={ layoutSetup } language='jsx' />
    </Section>

    <Section title='MDX Usage' description='Write normal fenced code in MDX. Titles, line highlights, and character highlights are parsed by rehype-pretty-code.'>
      <CodeBlock code={ mdxFenceUsage } language='mdx' />
    </Section>

    <Section title='Tabbed Code' description='Adjacent named fences are grouped by rehype-code-group-next, then CodeGroupTabs hydrates the generated tabs.'>
      <CodeBlock code={ mdxTabbedUsage } language='mdx' />
      <div className='mt-6'>
        <DemoCodeGroup />
      </div>
    </Section>
  </Page>
);

export default {
  parameters: pageParameters,
  tags: [ '!autodocs' ],
  title: 'MDX/Code Highlighting'
};

export const Default = {
  name: 'Overview',
  render: () => <CodeHighlightingDocs />
};
